export enum Templates {
    ACCESSIBILITY_STATEMENT = "accessibility-statement",
    ACTIVE_OFFICERS = "tasks/active-officers",
    CONFIRM_COMPANY = "confirm-company",
    ERROR_404 = "page-not-found",
    SERVICE_OFFLINE = "service-offline",
    SERVICE_OFFLINE_MID_JOURNEY = "service-offline-mid-journey",
    SIC = "tasks/sic",
    START = "start",
    STATEMENT_OF_CAPITAL = "tasks/statement-of-capital",
    TRADING_STATUS = "check-trading-status",
    INVALID_COMPANY_STATUS = "invalid-company-status",
    TASK_LIST = "task-list",
    USE_PAPER = "paper-filing",
    USE_WEBFILING = "use-webfiling",
    TRADING_STOP = "trading-stop",
    NO_FILING_REQUIRED = "no-filing-required",
    ACTIVE_PSCS = "tasks/active-pscs",
    WRONG_SIC = "incorrect-information/wrong-sic",
    WRONG_STATEMENT_OF_CAPITAL = "incorrect-information/wrong-statement-of-capital",
    WRONG_RO = "incorrect-information/wrong-ro",
    REGISTERED_OFFICE_ADDRESS = "tasks/registered-office-address"
}
